In [74]:
import numpy as np
import pandas as pd

### Creating data frame

In [9]:
df = pd.read_csv("Countries.csv")

### How to find how many rows and column are there

In [10]:
df.shape

(194, 64)

### Full info about data , we can find that there is NaN value or not.

In [ ]:
df.info()

# Analysis on Population

### Name of country and their capital which has highest population ?

In [47]:
print(df[df["population"] == df["population"].max()]["country"])
print(df[df["population"] == df["population"].max()]["capital_city"])

75    India
Name: country, dtype: object
75    New Delhi
Name: capital_city, dtype: object

### Name of country and their capital which has Lowest population ?

In [48]:
print(df[df["population"] == df["population"].min()]["country"]) 
print(df[df["population"] == df["population"].min()]["capital_city"])

179    Tuvalu
Name: country, dtype: object
179    Funafuti
Name: capital_city, dtype: object

### Top 10 most populated country in world.

In [73]:
most_populated = df.nlargest(10,"population")[["country","population"]]
most_populated

           country  population
75           India  1417173173
34           China  1412175000
184  United States   333287557
76       Indonesia   275501339
129       Pakistan   235824862
125        Nigeria   218541212
22          Brazil   215313498
12      Bangladesh   171186372
140         Russia   143555736
109         Mexico   127504125

### Top 10 least Populated Country in the World.

In [77]:
df.nsmallest(10,"population")[["country","population"]]

                 country  population
179               Tuvalu       11312
119                Nauru       12668
130                Palau       18055
143           San Marino       33660
112               Monaco       36469
97         Liechtenstein       39327
106     Marshall Islands       41569
159  St. Kitts and Nevis       47657
48              Dominica       72737
3                Andorra       79824

### Average Population of Country (in Crores upto 2 decimal)

In [91]:
avg_population_crore = df["population"].mean()/10000000
print(f"Average Population of a country is {avg_population_crore:.2f} Crore")

Average Population of a country is 4.08 Crore

### Which country has maximum Agricultural land

In [104]:
df[df["agricultural_land"] == df['agricultural_land'].max()][["country","agricultural_land"]]

   country  agricultural_land
34   China          5285080.0

### Which country has Maximum female Population

In [100]:
df[df["population_female"] == df["population_female"].max()][["country","population_female"]]

   country  population_female
34   China          691528501

## Top 5 country with highest democratic score

In [109]:
df.nlargest(5,"democracy_score")[["country",'democracy_score']]

      #OR

# df.sort_values(by="democracy_score",ascending=False).head()["country"]

         country  democracy_score
127       Norway             9.87
74       Iceland             9.58
164       Sweden             9.39
122  New Zealand             9.26
46       Denmark             9.22

### India's democratic score

In [110]:
print(df[df["country"] == "India"]["democracy_score"])

75    7.23
Name: democracy_score, dtype: float64

### How many total region are there?

In [20]:
print(df["region"].value_counts().count())

22

### How many country lies in Eastern Europe

In [116]:
print(df[df["region"] == "Eastern Europe"]["country"].count())

                #OR

# print(df["region"].value_counts()["Eastern Europe"])

10

### 2nd populated contry's leader name

In [22]:
df.sort_values(by="population",ascending=False).iloc[1]["political_leader"]

'Xi Jinping'

### How many country don't have political leader name

In [23]:
print(df[df["political_leader"].isna()]["country"].count())

7

### How many countries have "republic" in their country name(By using User_defined function)

In [32]:
count = 0
def check_republic(txt):
    global count
    if  "republic" in txt.lower():
        count += 1
    return txt

df["country_long"].apply(check_republic)
print(count)

125

### How many countries have "republic" in their country name

In [26]:
print(df["country_long"].str.contains("Republic", case=False).sum()) # it output in boolean 
# true -->1
#false --->0

125

### Highest population country in Africa

In [27]:
df[df["continent"] == "Africa"].nlargest(1,"population")

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.0,8.0,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President

# Created new data frame for Africa continent only.

In [28]:
africa_df = df[df["continent"] == "Africa"] #

125    Nigeria
Name: country, dtype: object

### Highest population country in Africa (using africa continent data frame)

In [35]:
africa_df[africa_df["population"] == africa_df["population"].max()]["country"]

125    Nigeria
Name: country, dtype: object